# Makefile frontend for scikit-build-core project
# Generated by buildgen for: cycdp
#
# This Makefile wraps common build commands for convenience.
# The actual build is handled by scikit-build-core via pyproject.toml

.PHONY: all sync build rebuild test lint format typecheck qa clean \
        distclean wheel sdist dist check publish-test publish upgrade \
        coverage coverage-html coverage-build docs release bump demos \
        demos-clean help stubs stubs-check sanitize tsan

# Default target
all: build

# Sync environment (initial setup, installs dependencies + package)
sync:
	@uv sync

# Build/rebuild the extension after code changes
build:
	@uv sync --reinstall-package cycdp

# Alias for build
rebuild: build

# Run tests
test:
	@uv run pytest tests/ -v

# Run all demos and generate WAV files to build/
demos:
	@echo "Running demos..."
	@mkdir -p build
	@for f in demos/[0-9]*.py; do \
		echo "=== Running $$(basename $$f) ==="; \
		uv run python "$$f"; \
	done
	@if [ -f demos/s01.wav ]; then \
		for f in demos/fx*.py; do \
			echo "=== Running $$(basename $$f) ==="; \
			uv run python "$$f" demos/s01.wav -o build; \
		done; \
	else \
		echo "Note: demos/s01.wav not found, skipping fx demos"; \
	fi
	@echo ""
	@echo "Generated $$(ls build/*.wav 2>/dev/null | wc -l | tr -d ' ') WAV files in build/"

# Clean demo output files
demos-clean:
	@rm -rf build/*.wav
	@echo "Cleaned build/*.wav"

# Lint with ruff
lint:
	@uv run ruff check --fix src/ tests/

# Format with ruff
format:
	@uv run ruff format src/ tests/

# Type check with mypy
typecheck:
	@uv run mypy src/cycdp/ tests/ --exclude '.venv'

# Regenerate src/cycdp/_core.pyi from _core.pyx
stubs:
	@uv run python scripts/gen_stubs.py

# Fail if the committed stubs are stale (CI)
stubs-check:
	@uv run python scripts/gen_stubs.py --check

# Run a full quality assurance check.
# format runs first so that lint and test see the formatted tree.
qa: format lint stubs-check typecheck test

# Build wheel
wheel:
	@uv build --wheel

# Build source distribution
sdist:
	@uv build --sdist

# Check distributions with twine
check:
	@uv run twine check dist/*

# Build both wheel and sdist
dist: wheel sdist check

# Release multiple versions
release:
	@uv build --sdist
	@uv build --wheel --python 3.10
	@uv build --wheel --python 3.11
	@uv build --wheel --python 3.12
	@uv build --wheel --python 3.13
	@uv build --wheel --python 3.14
	@uv run twine check dist/*

# Publish to TestPyPI
publish-test: check
	@uv run twine upload --repository testpypi dist/*

# Publish to PyPI
publish: check
	@uv run twine upload dist/*

# Upgrade all dependencies
upgrade:
	@uv lock --upgrade
	@uv sync

# Run tests with coverage.
#
# This rebuilds the extension with Cython line tracing (CYCDP_COVERAGE=ON) so
# that _core.pyx is actually measured. Without it, coverage silently reports on
# the pure-Python files only and the total is meaningless. --no-cache is
# required because uv keys its build cache on source content, not on the
# environment, and would otherwise hand back a non-instrumented wheel.
#
# The instrumented build is ~2x slower and must never be published; `make
# build` restores a normal one.
coverage: coverage-build
	@uv run pytest tests/ -v --cov --cov-report=term-missing

# Generate HTML coverage report
coverage-html: coverage-build
	@uv run pytest tests/ -v --cov --cov-report=html
	@echo "Coverage report: htmlcov/index.html"

# Build with ASan/UBSan and run the suite under them.
# Restores the normal extension on exit; run `make build` if interrupted.
sanitize:
	@bash scripts/run_sanitizers.sh

# Build with ThreadSanitizer and run the suite. Validates the GIL-releasing
# processing calls; TSan and ASan cannot be combined, so this is a separate run.
tsan:
	@CYCDP_SANITIZER=thread bash scripts/run_sanitizers.sh

# Rebuild the extension with line tracing enabled (used by the coverage targets)
coverage-build:
	@echo "Building instrumented extension (CYCDP_COVERAGE=ON)..."
	@SKBUILD_CMAKE_DEFINE=CYCDP_COVERAGE=ON \
		uv sync --dev --reinstall-package cycdp --no-cache

# Build documentation (requires sphinx in dev dependencies)
docs:
	@uv run sphinx-build -b html docs/ docs/_build/html

# Create a release (bump version, tag, push)
bump:
	@echo "Current version: $$(grep '^version' pyproject.toml | head -1)"
	@read -p "New version: " version; 	sed -i '' "s/^version = .*/version = \"$$version\"/" pyproject.toml; 	git add pyproject.toml; 	git commit -m "Bump version to $$version"; 	git tag -a "v$$version" -m "Release $$version"; 	echo "Tagged v$$version. Run 'git push && git push --tags' to publish."

# Clean build artifacts
clean:
	@rm -rf build/
	@rm -rf dist/
	@rm -f src/cycdp/_core.c
	@rm -rf *.egg-info/
	@rm -rf src/*.egg-info/
	@rm -rf .pytest_cache/
	@rm -rf demos/build/
	@rm -rf build/*.wav
	@find . -name "*.so" -delete
	@find . -name "*.pyd" -delete
	@find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

# Clean everything including CMake cache
distclean: clean
	@rm -rf CMakeCache.txt CMakeFiles/

# Show help
help:
	@echo "Available targets:"
	@echo "  all          - Build/rebuild the extension (default)"
	@echo "  sync         - Sync environment (initial setup)"
	@echo "  build        - Rebuild extension after code changes"
	@echo "  rebuild      - Alias for build"
	@echo "  test         - Run tests"
	@echo "  demos        - Run all demos and generate WAV files to build/"
	@echo "  demos-clean  - Clean demo output files"
	@echo "  lint         - Lint with ruff"
	@echo "  format       - Format with ruff"
	@echo "  typecheck    - Type check with mypy"
	@echo "  stubs        - Regenerate _core.pyi from _core.pyx"
	@echo "  stubs-check  - Fail if committed stubs are stale"
	@echo "  qa           - Run full QA (format, lint, stubs-check, typecheck, test)"
	@echo "  wheel        - Build wheel distribution"
	@echo "  sdist        - Build source distribution"
	@echo "  dist         - Build both wheel and sdist"
	@echo "  check        - Check distributions with twine"
	@echo "  publish-test - Publish to TestPyPI"
	@echo "  publish      - Publish to PyPI"
	@echo "  upgrade      - Upgrade all dependencies"
	@echo "  coverage     - Rebuild with line tracing, run tests with coverage"
	@echo "  coverage-html- Same, with an HTML report"
	@echo "  sanitize     - Build with ASan/UBSan and run tests under them"
	@echo "  tsan         - Build with ThreadSanitizer and run tests under it"
	@echo "  docs         - Build documentation with Sphinx"
	@echo "  release      - Bump version, tag, and prepare release"
	@echo "  clean        - Remove build artifacts"
	@echo "  distclean    - Remove all generated files"
	@echo "  help         - Show this help message"
