"""Type stubs for cycdp._core Cython extension module.

The function section below is generated from _core.pyx by scripts/gen_stubs.py
(`make stubs`). Everything above the sentinel is hand-written. Do not edit the
generated section: tests/test_signatures.py asserts that this file agrees with
the compiled module, so hand edits will fail the test suite.
"""

from collections.abc import Iterator, Sequence
from typing import Any, Protocol, runtime_checkable

# Type alias for buffer-like objects (numpy arrays, array.array('f'), memoryview, etc.)
# In practice, any object supporting the buffer protocol with float32 data

@runtime_checkable
class BufferLike(Protocol):
    """Protocol for objects supporting the buffer protocol with float32 data."""
    def __buffer__(self, flags: int) -> memoryview: ...

# =============================================================================
# Constants
# =============================================================================

FLAG_NONE: int
FLAG_CLIP: int

# Waveform types for synth_wave
WAVE_SINE: int
WAVE_SQUARE: int
WAVE_SAW: int
WAVE_RAMP: int
WAVE_TRIANGLE: int

# Scramble modes
SCRAMBLE_SHUFFLE: int
SCRAMBLE_REVERSE: int
SCRAMBLE_SIZE_UP: int
SCRAMBLE_SIZE_DOWN: int
SCRAMBLE_LEVEL_UP: int
SCRAMBLE_LEVEL_DOWN: int

# =============================================================================
# Exception
# =============================================================================

class CDPError(Exception):
    """Exception raised for CDP library errors."""

    code: int
    def __init__(self, code: int, message: str) -> None: ...

# =============================================================================
# Utility functions
# =============================================================================

def version() -> str:
    """Get CDP library version string."""
    ...

def gain_to_db(gain: float) -> float:
    """Convert linear gain to decibels."""
    ...

def db_to_gain(db: float) -> float:
    """Convert decibels to linear gain."""
    ...

# =============================================================================
# Classes
# =============================================================================

class Context:
    """CDP processing context."""
    def __init__(self) -> None: ...
    def get_error(self) -> int:
        """Get last error code."""
        ...
    def get_error_message(self) -> str:
        """Get last error message."""
        ...
    def clear_error(self) -> None:
        """Clear error state."""
        ...

class Buffer:
    """CDP audio buffer with Python buffer protocol support.

    Satisfies BufferLike: Buffer exports the C-level buffer protocol via
    __getbuffer__, so memoryview(buf) works and it can be passed anywhere a
    raw float32 buffer is accepted. It is also iterable through the legacy
    __getitem__/__len__ protocol. Neither was declared here, so type checkers
    rejected `peak(buf)`, `memoryview(buf)` and `for x in buf` -- all of which
    work at runtime.
    """

    def __buffer__(self, flags: int) -> memoryview: ...
    def __iter__(self) -> Iterator[float]: ...
    @staticmethod
    def create(frame_count: int, channels: int = 1, sample_rate: int = 44100) -> Buffer:
        """Create a new buffer with allocated memory."""
        ...

    @staticmethod
    def from_memoryview(
        samples: BufferLike, channels: int = 1, sample_rate: int = 44100
    ) -> Buffer:
        """Create a buffer by copying from a memoryview."""
        ...

    def to_list(self) -> list[float]:
        """Convert buffer to Python list."""
        ...

    def to_bytes(self) -> bytes:
        """Convert buffer to bytes (raw float32 data)."""
        ...

    @property
    def sample_count(self) -> int: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def channels(self) -> int: ...
    @property
    def sample_rate(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def clear(self) -> None:
        """Set all samples to zero."""
        ...

# ==== GENERATED BY scripts/gen_stubs.py -- DO NOT EDIT BELOW THIS LINE ====
# Regenerate with: make stubs

def _live_thread_contexts() -> int:
    """Number of per-thread processing contexts currently alive."""
    ...

def apply_gain(ctx: Context, buf: Buffer, gain: float, clip: bool = False) -> None:
    """Apply gain to buffer (in-place)."""
    ...

def apply_gain_db(
    ctx: Context,
    buf: Buffer,
    gain_db: float,
    clip: bool = False,
) -> None:
    """Apply gain in dB to buffer (in-place)."""
    ...

def apply_normalize(ctx: Context, buf: Buffer, target_level: float = 1.0) -> None:
    """Normalize buffer to target level (in-place)."""
    ...

def apply_normalize_db(ctx: Context, buf: Buffer, target_db: float = 0.0) -> None:
    """Normalize buffer to target dB level (in-place)."""
    ...

def apply_phase_invert(ctx: Context, buf: Buffer) -> None:
    """Invert phase of buffer (in-place)."""
    ...

def attack(buf: Buffer, attack_gain: float, attack_time: float) -> Buffer:
    """Modify the attack portion of a sound (native implementation)."""
    ...

def bitcrush(buf: Buffer, bit_depth: int = 8, downsample: int = 1) -> Buffer:
    """Apply bitcrusher effect (native implementation)."""
    ...

def bounce(
    buf: Buffer,
    bounces: int = 8,
    initial_delay: float = 0.5,
    shrink: float = 0.7,
    end_level: float = 0.1,
    level_curve: float = 1.0,
    cut_bounces: bool = False,
) -> Buffer:
    """Bounce - bouncing ball effect."""
    ...

def brassage(
    buf: Buffer,
    velocity: float = 1.0,
    density: float = 1.0,
    grainsize_ms: float = 50.0,
    scatter: float = 0.0,
    pitch_shift: float = 0.0,
    amp_variation: float = 0.0,
    seed: int = 0,
) -> Buffer:
    """Apply granular brassage (native implementation)."""
    ...

def brownian(
    buf: Buffer,
    step_size: float = 0.1,
    smoothing: float = 0.9,
    target: int = 0,
    seed: int = 0,
) -> Buffer:
    """Brownian (random walk) modulation."""
    ...

def cantor(
    buf: Buffer,
    depth: int = 4,
    duty_cycle: float = 0.5,
    smooth_ms: float = 5.0,
    seed: int = 0,
) -> Buffer:
    """Cantor set gating - fractal silence pattern."""
    ...

def cascade(
    buf: Buffer,
    num_echoes: int = 6,
    delay_ms: float = 100.0,
    pitch_decay: float = 0.95,
    amp_decay: float = 0.7,
    filter_decay: float = 0.8,
    seed: int = 0,
) -> Buffer:
    """Cascade - cascading echoes with progressive transformation."""
    ...

def chirikov(
    buf: Buffer,
    k_param: float = 2.0,
    mod_depth: float = 0.5,
    rate: float = 2.0,
    seed: int = 0,
) -> Buffer:
    """Chirikov map modulation - chaotic standard map."""
    ...

def chorus(
    buf: Buffer,
    rate: float = 1.5,
    depth_ms: float = 5.0,
    mix: float = 0.5,
) -> Buffer:
    """Apply chorus effect (native implementation)."""
    ...

def compressor(
    buf: Buffer,
    threshold_db: float = -20.0,
    ratio: float = 4.0,
    attack_ms: float = 10.0,
    release_ms: float = 100.0,
    makeup_gain_db: float = 0.0,
) -> Buffer:
    """Apply dynamic range compression (native implementation)."""
    ...

def concat(buffers: list[Buffer]) -> Buffer:
    """Concatenate multiple buffers into one."""
    ...

def constrict(buf: Buffer, constriction: float = 50.0) -> Buffer:
    """Apply constrict effect - shorten or remove silent sections."""
    ...

def cross_synth(
    buf1: Buffer,
    buf2: Buffer,
    mode: int = 0,
    mix: float = 1.0,
    fft_size: int = 1024,
) -> Buffer:
    """Cross-synthesis: combine amplitude from one sound with frequencies from another."""
    ...

def crystal(
    buf: Buffer,
    density: float = 50.0,
    decay: float = 0.5,
    pitch_scatter: float = 2.0,
    seed: int = 0,
) -> Buffer:
    """Crystal textures - granular with decaying echoes."""
    ...

def delay(
    buf: Buffer,
    delay_ms: float,
    feedback: float = 0.3,
    mix: float = 0.5,
) -> Buffer:
    """Apply delay effect with feedback (native implementation)."""
    ...

def distort_cut(
    buf: Buffer,
    cycle_count: int = 4,
    cycle_step: int = 4,
    exponent: float = 1.0,
    min_level: float = 0.0,
) -> Buffer:
    """Cut sound into waveset segments with decaying envelope."""
    ...

def distort_fractal(buf: Buffer, scaling: float, loudness: float = 1.0) -> Buffer:
    """Apply fractal distortion (native implementation)."""
    ...

def distort_mark(
    buf: Buffer,
    markers: Sequence[float],
    unit_ms: float = 10.0,
    stretch: float = 1.0,
    random: float = 0.0,
    flip_phase: bool = False,
    seed: int = 0,
) -> Buffer:
    """Interpolate between waveset-groups at marked time positions."""
    ...

def distort_overload(buf: Buffer, clip_level: float, depth: float = 0.5) -> Buffer:
    """Apply clipping distortion (native implementation)."""
    ...

def distort_repeat(
    buf: Buffer,
    multiplier: int = 2,
    cycle_count: int = 1,
    skip_cycles: int = 0,
    splice_ms: float = 15.0,
    mode: int = 0,
) -> Buffer:
    """Time-stretch by repeating wavecycles."""
    ...

def distort_reverse(buf: Buffer, cycle_count: int) -> Buffer:
    """Reverse groups of wavecycles (native implementation)."""
    ...

def distort_shift(
    buf: Buffer,
    group_size: int = 1,
    shift: int = 1,
    mode: int = 0,
) -> Buffer:
    """Shift or swap half-wavecycle groups for phase distortion."""
    ...

def distort_shuffle(buf: Buffer, chunk_count: int, seed: int = 0) -> Buffer:
    """Shuffle segments of audio (native implementation)."""
    ...

def distort_warp(
    buf: Buffer,
    warp: float = 0.001,
    mode: int = 0,
    waveset_count: int = 1,
) -> Buffer:
    """Apply progressive warp distortion with modular sample folding."""
    ...

def dovetail(
    buf: Buffer,
    fade_in_dur: float,
    fade_out_dur: float,
    fade_type: str = "exponential",
) -> Buffer:
    """Apply fade-in and fade-out envelopes (native implementation)."""
    ...

def drunk(
    buf: Buffer,
    duration: float = 5.0,
    step_ms: float = 100.0,
    step_rand: float = 0.3,
    locus: float = 0.0,
    ambitus: float = 0.0,
    overlap: float = 0.1,
    splice_ms: float = 15.0,
    seed: int = 0,
) -> Buffer:
    """Drunk - drunken walk random navigation through audio."""
    ...

def envelope_apply(buf: Buffer, envelope: Buffer, depth: float = 1.0) -> Buffer:
    """Apply an envelope to audio (native implementation)."""
    ...

def envelope_follow(
    buf: Buffer,
    attack_ms: float = 10.0,
    release_ms: float = 100.0,
    mode: str = "peak",
) -> Buffer:
    """Extract amplitude envelope from audio (native implementation)."""
    ...

def eq_parametric(
    buf: Buffer,
    center_freq: float,
    gain_db: float,
    q: float = 1.0,
    fft_size: int = 1024,
) -> Buffer:
    """Apply parametric EQ (native implementation)."""
    ...

def extract_channel(buf: Buffer, channel: int) -> Buffer:
    """Extract a single channel from a multi-channel buffer."""
    ...

def fade_in(buf: Buffer, duration: float, curve: str = "linear") -> Buffer:
    """Apply fade in to buffer (in-place)."""
    ...

def fade_out(buf: Buffer, duration: float, curve: str = "linear") -> Buffer:
    """Apply fade out to buffer (in-place)."""
    ...

def filter_bandpass(
    buf: Buffer,
    low_freq: float,
    high_freq: float,
    attenuation_db: float = -60,
    fft_size: int = 1024,
) -> Buffer:
    """Apply bandpass filter (native implementation)."""
    ...

def filter_highpass(
    buf: Buffer,
    cutoff_freq: float,
    attenuation_db: float = -60,
    fft_size: int = 1024,
) -> Buffer:
    """Apply highpass filter (native implementation)."""
    ...

def filter_lowpass(
    buf: Buffer,
    cutoff_freq: float,
    attenuation_db: float = -60,
    fft_size: int = 1024,
) -> Buffer:
    """Apply lowpass filter (native implementation)."""
    ...

def filter_notch(
    buf: Buffer,
    center_freq: float,
    width_hz: float,
    attenuation_db: float = -60,
    fft_size: int = 1024,
) -> Buffer:
    """Apply notch (band-reject) filter (native implementation)."""
    ...

def flanger(
    buf: Buffer,
    rate: float = 0.5,
    depth_ms: float = 3.0,
    feedback: float = 0.5,
    mix: float = 0.5,
) -> Buffer:
    """Apply flanger effect (native implementation)."""
    ...

def flutter(
    buf: Buffer,
    frequency: float = 4.0,
    depth: float = 1.0,
    gain: float = 1.0,
    randomize: bool = False,
) -> Buffer:
    """Apply flutter (spatial tremolo) effect."""
    ...

def fofex_extract(
    buf: Buffer,
    time: float,
    fof_count: int = 1,
    window: bool = True,
) -> Buffer:
    """Extract a single FOF (pitch-synchronous grain) at a specified time."""
    ...

def fofex_extract_all(
    buf: Buffer,
    fof_count: int = 1,
    min_level_db: float = 0.0,
    window: bool = True,
) -> tuple[Buffer, int, int]:
    """Extract all FOFs from audio file."""
    ...

def fofex_repitch(
    buf: Buffer,
    pitch_shift: float,
    preserve_formants: bool = True,
) -> Buffer:
    """Resynthesize audio with modified pitch using FOFs."""
    ...

def fofex_synth(
    fof_bank: Buffer,
    duration: float,
    frequency: float,
    amplitude: float = 0.8,
    fof_index: int = -1,
    fof_unit_len: int = 0,
) -> Buffer:
    """Synthesize audio using extracted FOFs."""
    ...

def formants(
    buf: Buffer,
    lpc_order: int = 12,
    frame_size: int = 1024,
    hop_size: int = 256,
) -> dict[str, Any]:
    """Extract formant frequencies from audio using LPC analysis."""
    ...

def fractal(
    buf: Buffer,
    depth: int = 3,
    pitch_ratio: float = 0.5,
    decay: float = 0.7,
    seed: int = 0,
) -> Buffer:
    """Fractal processing - self-similar recursive layering."""
    ...

def fracture(
    buf: Buffer,
    fragment_ms: float = 50.0,
    gap_ratio: float = 0.5,
    scatter: float = 0.3,
    seed: int = 0,
) -> Buffer:
    """Fracture - break audio into fragments with gaps."""
    ...

def freeze(
    buf: Buffer,
    start_time: float,
    end_time: float,
    duration: float,
    delay: float = 0.05,
    randomize: float = 0.2,
    pitch_scatter: float = 0.0,
    amp_cut: float = 0.1,
    gain: float = 1.0,
    seed: int = 0,
) -> Buffer:
    """Freeze a segment of audio by repeated iteration (native implementation)."""
    ...

def gain(
    samples: BufferLike,
    gain_factor: float = 1.0,
    sample_rate: int = 44100,
    clip: bool = False,
) -> Buffer:
    """Apply gain to audio samples."""
    ...

def gain_db(
    samples: BufferLike,
    db: float = 0.0,
    sample_rate: int = 44100,
    clip: bool = False,
) -> Buffer:
    """Apply gain in decibels to audio samples."""
    ...

def gate(
    buf: Buffer,
    threshold_db: float,
    attack_ms: float = 1.0,
    release_ms: float = 50.0,
    hold_ms: float = 10.0,
) -> Buffer:
    """Apply noise gate (native implementation)."""
    ...

def get_partials(
    buf: Buffer,
    min_amp_db: float = -60.0,
    max_partials: int = 100,
    freq_tolerance: float = 50.0,
    fft_size: int = 2048,
    hop_size: int = 512,
) -> dict[str, Any]:
    """Extract sinusoidal partials from audio using peak tracking."""
    ...

def get_peak(ctx: Context, buf: Buffer) -> tuple[float, int]:
    """Find peak level in buffer. Returns (level, frame_position)."""
    ...

def grain_cloud(
    buf: Buffer,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
    density: float = 10.0,
    duration: float = 0.0,
    scatter: float = 0.3,
    seed: int = 0,
) -> Buffer:
    """Generate grain cloud from source audio (CDP: grain)."""
    ...

def grain_duplicate(
    buf: Buffer,
    repeats: int = 2,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
    seed: int = 0,
) -> Buffer:
    """Repeat grains (CDP: GRAIN DUPLICATE)."""
    ...

def grain_extend(
    buf: Buffer,
    grainsize_ms: float = 15.0,
    trough: float = 0.3,
    extension: float = 1.0,
    start_time: float = 0.0,
    end_time: float = 0.0,
    seed: int = 0,
) -> Buffer:
    """Extend audio duration using grain repetition (CDP: grainex extend)."""
    ...

def grain_omit(
    buf: Buffer,
    keep: int = 1,
    out_of: int = 2,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
    seed: int = 0,
) -> Buffer:
    """Selectively remove grains (CDP: GRAIN OMIT)."""
    ...

def grain_position(
    buf: Buffer,
    positions: list[float] | None = None,
    duration: float = 0.0,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
) -> Buffer:
    """Position grains at specific times (CDP: GRAIN POSITION)."""
    ...

def grain_reorder(
    buf: Buffer,
    order: list[int] | None = None,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
    seed: int = 0,
) -> Buffer:
    """Reorder grains in audio (CDP: GRAIN REORDER)."""
    ...

def grain_repitch(
    buf: Buffer,
    pitch_semitones: float = 0.0,
    pitch_curve: Sequence[tuple[float, float]] | None = None,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
) -> Buffer:
    """Variable pitch shifting per grain (CDP: GRAIN REPITCH)."""
    ...

def grain_rerhythm(
    buf: Buffer,
    times: list[float] | None = None,
    ratios: list[float] | None = None,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
    seed: int = 0,
) -> Buffer:
    """Change the timing between grains (CDP: GRAIN RERHYTHM)."""
    ...

def grain_reverse(buf: Buffer, gate: float = 0.1, grainsize_ms: float = 50.0) -> Buffer:
    """Reverse the order of grains (CDP: GRAIN REVERSE)."""
    ...

def grain_timewarp(
    buf: Buffer,
    stretch: float = 1.0,
    stretch_curve: Sequence[tuple[float, float]] | None = None,
    gate: float = 0.1,
    grainsize_ms: float = 50.0,
) -> Buffer:
    """Non-linear time stretch of grain sequence (CDP: GRAIN TIMEWARP)."""
    ...

def hover(
    buf: Buffer,
    frequency: float = 440.0,
    location: float = 0.5,
    frq_rand: float = 0.1,
    loc_rand: float = 0.1,
    splice_ms: float = 1.0,
    duration: float = 0.0,
) -> Buffer:
    """Apply hover effect - zigzag reading at specified frequency."""
    ...

def interleave(buffers: list[Buffer]) -> Buffer:
    """Interleave multiple mono buffers into a single multi-channel buffer."""
    ...

def iterate(
    buf: Buffer,
    repeats: int = 4,
    delay: float = 0.5,
    delay_rand: float = 0.0,
    pitch_shift: float = 0.0,
    gain_decay: float = 1.0,
    seed: int = 0,
) -> Buffer:
    """Iterate - repeat audio with variations."""
    ...

def limiter(
    buf: Buffer,
    threshold_db: float = -0.1,
    attack_ms: float = 0.0,
    release_ms: float = 50.0,
) -> Buffer:
    """Apply limiting to prevent clipping (native implementation)."""
    ...

def loop(
    buf: Buffer,
    start: float = 0.0,
    length_ms: float = 500.0,
    step_ms: float = 0.0,
    search_ms: float = 0.0,
    repeats: int = 4,
    splice_ms: float = 15.0,
    seed: int = 0,
) -> Buffer:
    """Loop - loop a section of audio with variations."""
    ...

def merge_channels(left: Buffer, right: Buffer) -> Buffer:
    """Merge two mono buffers into a stereo buffer."""
    ...

def mirror(buf: Buffer) -> Buffer:
    """Mirror (swap) left and right channels of a stereo buffer."""
    ...

def mix(buffers: list[Buffer], gains: list[float] | None = None) -> Buffer:
    """Mix multiple buffers together with optional gains."""
    ...

def mix2(a: Buffer, b: Buffer, gain_a: float = 1.0, gain_b: float = 1.0) -> Buffer:
    """Mix two buffers together with optional gains."""
    ...

def modify_speed(buf: Buffer, speed_factor: float) -> Buffer:
    """Change playback speed (native implementation)."""
    ...

def morph(
    buf1: Buffer,
    buf2: Buffer,
    morph_start: float = 0.0,
    morph_end: float = 1.0,
    exponent: float = 1.0,
    fft_size: int = 1024,
) -> Buffer:
    """Spectral morph between two sounds (CDP: SPECMORPH)."""
    ...

def morph_bridge_native(
    buf1: Buffer,
    buf2: Buffer,
    mode: int = 0,
    offset: float = 0.0,
    interp_start: float = 0.0,
    interp_end: float = 1.0,
    fft_size: int = 1024,
) -> Buffer:
    """Spectral bridge, ported from CDP's specbridge."""
    ...

def morph_glide(
    buf1: Buffer,
    buf2: Buffer,
    duration: float = 1.0,
    fft_size: int = 1024,
) -> Buffer:
    """Simple spectral glide between two sounds (CDP: SPECGLIDE)."""
    ...

def morph_glide_native(
    buf1: Buffer,
    buf2: Buffer,
    duration: float = 1.0,
    fft_size: int = 1024,
) -> Buffer:
    """Spectral glide, ported from CDP's specglide."""
    ...

def morph_native(
    buf1: Buffer,
    buf2: Buffer,
    mode: int = 0,
    amp_start: float = 0.0,
    amp_end: float = 1.0,
    freq_start: float = 0.0,
    freq_end: float = 1.0,
    amp_exp: float = 1.0,
    freq_exp: float = 1.0,
    stagger: float = 0.0,
    fft_size: int = 1024,
) -> Buffer:
    """Full spectral morph, ported from CDP's specmorph."""
    ...

def narrow(buf: Buffer, width: float = 1.0) -> Buffer:
    """Narrow or widen stereo image."""
    ...

def normalize(
    samples: BufferLike,
    target: float = 1.0,
    sample_rate: int = 44100,
) -> Buffer:
    """Normalize audio to target peak level."""
    ...

def normalize_db(
    samples: BufferLike,
    target_db: float = 0.0,
    sample_rate: int = 44100,
) -> Buffer:
    """Normalize audio to target peak level in dB."""
    ...

def pan(buf: Buffer, position: float = 0.0) -> Buffer:
    """Pan a mono buffer to stereo with a static pan position."""
    ...

def pan_envelope(buf: Buffer, points: Sequence[tuple[float, float]]) -> Buffer:
    """Pan a mono buffer to stereo with time-varying position."""
    ...

def peak(samples: BufferLike, sample_rate: int = 44100) -> tuple[float, int]:
    """Find peak level in audio samples."""
    ...

def phase_invert(samples: Buffer | BufferLike, sample_rate: int = 44100) -> Buffer:
    """Invert the phase of an audio signal."""
    ...

def phase_stereo(buf: Buffer, transfer: float = 1.0) -> Buffer:
    """Enhance stereo separation using phase subtraction."""
    ...

def pitch(
    buf: Buffer,
    min_freq: float = 50.0,
    max_freq: float = 2000.0,
    frame_size: int = 2048,
    hop_size: int = 512,
) -> dict[str, Any]:
    """Extract pitch contour from audio using YIN algorithm."""
    ...

def pitch_shift(buf: Buffer, semitones: float, fft_size: int = 1024) -> Buffer:
    """Pitch shift without changing duration (native implementation)."""
    ...

def psow_dupl(buf: Buffer, repeat_count: int = 2, grain_count: int = 1) -> Buffer:
    """Duplicate pitch-synchronous grains for time-stretching."""
    ...

def psow_grab(
    buf: Buffer,
    time: float = 0.0,
    duration: float = 0.0,
    grain_count: int = 1,
    density: float = 1.0,
) -> Buffer:
    """Extract pitch-synchronous grains from a position in the audio."""
    ...

def psow_interp(
    grain1: Buffer,
    grain2: Buffer,
    start_dur: float = 0.1,
    interp_dur: float = 0.5,
    end_dur: float = 0.1,
) -> Buffer:
    """Interpolate between two pitch-synchronous grains."""
    ...

def psow_stretch(
    buf: Buffer,
    stretch_factor: float = 1.0,
    grain_count: int = 1,
) -> Buffer:
    """Time-stretch audio while preserving pitch using PSOLA."""
    ...

def quirk(
    buf: Buffer,
    probability: float = 0.3,
    intensity: float = 0.5,
    mode: int = 2,
    seed: int = 0,
) -> Buffer:
    """Quirk - unpredictable glitchy transformations."""
    ...

def read_file(path: str) -> Buffer:
    """Read an audio file into a Buffer."""
    ...

def release_thread_context() -> None:
    """Free this thread's processing context now."""
    ...

def retime(
    buf: Buffer,
    ratio: float = 1.0,
    grain_ms: float = 50.0,
    overlap: float = 0.5,
) -> Buffer:
    """Time-domain time stretching/compression using overlap-add (TDOLA)."""
    ...

def reverb(
    buf: Buffer,
    mix: float = 0.5,
    decay_time: float = 2.0,
    damping: float = 0.5,
    lpfreq: float = 8000.0,
    predelay: float = 0.0,
) -> Buffer:
    """Apply reverb (native implementation)."""
    ...

def reverse(buf: Buffer) -> Buffer:
    """Reverse audio buffer."""
    ...

def ring_mod(buf: Buffer, freq: float, mix: float = 1.0) -> Buffer:
    """Apply ring modulation (native implementation)."""
    ...

def rotor(
    buf: Buffer,
    pitch_rate: float = 1.0,
    pitch_depth: float = 2.0,
    amp_rate: float = 1.5,
    amp_depth: float = 0.5,
    phase_offset: float = 0.0,
) -> Buffer:
    """Apply dual-rotation modulation effect."""
    ...

def scramble(buf: Buffer, mode: int = 0, group_size: int = 2, seed: int = 0) -> Buffer:
    """Reorder wavesets (zero-crossing segments) in audio."""
    ...

def spectral_blur(buf: Buffer, blur_time: float, fft_size: int = 1024) -> Buffer:
    """Apply spectral blur (native implementation)."""
    ...

def spectral_clean(
    buf: Buffer,
    threshold_db: float = -40.0,
    fft_size: int = 1024,
) -> Buffer:
    """Spectral noise gate - zero bins below per-frame threshold."""
    ...

def spectral_focus(
    buf: Buffer,
    center_freq: float = 1000.0,
    bandwidth: float = 200.0,
    gain_db: float = 6.0,
    fft_size: int = 1024,
) -> Buffer:
    """Enhance frequencies around a center point with super-Gaussian curve."""
    ...

def spectral_fold(
    buf: Buffer,
    fold_freq: float = 2000.0,
    fft_size: int = 1024,
) -> Buffer:
    """Fold spectrum at frequency (creates metallic, inharmonic effects)."""
    ...

def spectral_hilite(
    buf: Buffer,
    threshold_db: float = -20.0,
    boost_db: float = 6.0,
    fft_size: int = 1024,
) -> Buffer:
    """Boost spectral peaks above threshold."""
    ...

def spectral_shift(buf: Buffer, shift_hz: float, fft_size: int = 1024) -> Buffer:
    """Shift all frequencies by a fixed Hz offset (native implementation)."""
    ...

def spectral_stretch(
    buf: Buffer,
    max_stretch: float,
    freq_divide: float = 1000.0,
    exponent: float = 1.0,
    fft_size: int = 1024,
) -> Buffer:
    """Stretch frequencies differentially (native implementation)."""
    ...

def spin(
    buf: Buffer,
    rate: float = 1.0,
    doppler: float = 0.0,
    depth: float = 1.0,
) -> Buffer:
    """Rotate audio around the stereo field."""
    ...

def splinter(
    buf: Buffer,
    start: float = 0.0,
    duration_ms: float = 50.0,
    repeats: int = 20,
    min_shrink: float = 0.1,
    shrink_curve: float = 1.0,
    accel: float = 1.5,
    seed: int = 0,
) -> Buffer:
    """Create fragmenting/splintering effect by shrinking and repeating a segment."""
    ...

def split_channels(buf: Buffer) -> list[Buffer]:
    """Split a multi-channel buffer into separate mono buffers."""
    ...

def strange(
    buf: Buffer,
    chaos_amount: float = 0.5,
    rate: float = 2.0,
    seed: int = 0,
) -> Buffer:
    """Strange attractor (Lorenz) modulation."""
    ...

def stutter(
    buf: Buffer,
    segment_ms: float = 100.0,
    duration: float = 5.0,
    silence_prob: float = 0.2,
    silence_min_ms: float = 10.0,
    silence_max_ms: float = 100.0,
    transpose_range: float = 0.0,
    seed: int = 0,
) -> Buffer:
    """Stutter - segment-based stuttering effect."""
    ...

def synth_chord(
    midi_notes: Sequence[int],
    amplitude: float = 0.8,
    duration: float = 1.0,
    detune_cents: float = 0.0,
    sample_rate: int = 44100,
    channels: int = 1,
) -> Buffer:
    """Generate chord from MIDI notes."""
    ...

def synth_click(
    tempo: float = 120.0,
    beats_per_bar: int = 4,
    duration: float = 10.0,
    click_freq: float = 1000.0,
    click_dur_ms: float = 10.0,
    sample_rate: int = 44100,
) -> Buffer:
    """Generate click track."""
    ...

def synth_noise(
    pink: int = 0,
    amplitude: float = 0.8,
    duration: float = 1.0,
    sample_rate: int = 44100,
    channels: int = 1,
    seed: int = 0,
) -> Buffer:
    """Generate noise."""
    ...

def synth_wave(
    waveform: int = WAVE_SINE,
    frequency: float = 440.0,
    amplitude: float = 0.8,
    duration: float = 1.0,
    sample_rate: int = 44100,
    channels: int = 1,
) -> Buffer:
    """Generate basic waveforms."""
    ...

def tesselate(
    buf: Buffer,
    tile_ms: float = 50.0,
    pattern: int = 1,
    overlap: float = 0.25,
    transform: float = 0.3,
    seed: int = 0,
) -> Buffer:
    """Tesselate - tile audio segments in patterns."""
    ...

def texture_multi(
    buf: Buffer,
    duration: float = 5.0,
    density: float = 2.0,
    group_size: int = 4,
    group_spread: float = 0.2,
    pitch_range: float = 8.0,
    pitch_center: float = 0.0,
    amp_decay: float = 0.3,
    seed: int = 0,
) -> Buffer:
    """Generate multi-layer texture (CDP: texture GROUPS)."""
    ...

def texture_simple(
    buf: Buffer,
    duration: float = 5.0,
    density: float = 5.0,
    pitch_range: float = 6.0,
    amp_range: float = 0.3,
    spatial_range: float = 0.8,
    seed: int = 0,
) -> Buffer:
    """Generate simple texture (CDP: texture SIMPLE_TEX)."""
    ...

def time_stretch(
    buf: Buffer,
    factor: float,
    fft_size: int = 1024,
    overlap: int = 3,
) -> Buffer:
    """Time-stretch audio without changing pitch (native implementation)."""
    ...

def to_mono(buf: Buffer) -> Buffer:
    """Convert multi-channel buffer to mono by averaging all channels."""
    ...

def to_stereo(buf: Buffer) -> Buffer:
    """Convert mono buffer to stereo by duplicating the channel."""
    ...

def tremolo(buf: Buffer, freq: float, depth: float, gain: float = 1.0) -> Buffer:
    """Apply tremolo / amplitude modulation (native implementation)."""
    ...

def wrappage(
    buf: Buffer,
    grain_size: float = 50.0,
    density: float = 1.0,
    velocity: float = 1.0,
    pitch: float = 0.0,
    spread: float = 1.0,
    jitter: float = 0.1,
    splice_ms: float = 5.0,
    duration: float = 0.0,
    seed: int = 0,
) -> Buffer:
    """Apply wrappage effect - granular texture with stereo spatial distribution."""
    ...

def write_file(path: str, buf: Buffer, format: str = "float") -> None:
    """Write a Buffer to an audio file."""
    ...

def zigzag(buf: Buffer, times: Sequence[float], splice_ms: float = 15.0) -> Buffer:
    """Zigzag playback - alternates between forward and backward playback."""
    ...
