#!/usr/bin/env python3
"""Generate the function section of src/cycdp/_core.pyi from _core.pyx.

Parameter names, order and defaults are read from the Cython source, which is
the only authoritative description of the runtime API. Return types and the
annotations for parameters the .pyx leaves untyped live in the tables below,
because Cython `def` functions carry no return-type information.

Everything in _core.pyi above the SENTINEL line is hand-written and preserved
verbatim: the imports, the BufferLike protocol, the constants, and the
CDPError/Context/Buffer class stubs. Everything below it is regenerated.

Usage:
    make stubs             # rewrite src/cycdp/_core.pyi
    make stubs-check       # exit 1 if the stub is stale (used in CI)

tests/test_signatures.py independently asserts that the committed stub agrees
with the compiled module, so drift fails the test suite even if this script is
never run.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PYX = REPO / "src" / "cycdp" / "_core.pyx"
PYI = REPO / "src" / "cycdp" / "_core.pyi"

SENTINEL = (
    "# ==== GENERATED BY scripts/gen_stubs.py -- DO NOT EDIT BELOW THIS LINE ===="
)

# Cython parameter type -> stub annotation.
TYPE_MAP = {
    "double": "float",
    "float": "float",
    "int": "int",
    "unsigned int": "int",
    "long": "int",
    "size_t": "int",
    "bint": "bool",
    "str": "str",
    "Buffer": "Buffer",
    "Context": "Context",
    "float[::1]": "BufferLike",
}

# Return annotations. Cython `def` functions return generic Python objects, so
# these cannot be derived from the source and must be declared here.
RETURNS = {
    "apply_gain": "None",
    "apply_gain_db": "None",
    "apply_normalize": "None",
    "apply_normalize_db": "None",
    "apply_phase_invert": "None",
    "formants": "list[list[tuple[float, float]]]",
    "get_partials": "list[tuple[float, float, float]]",
    "get_peak": "tuple[float, int]",
    "peak": "tuple[float, int]",
    "pitch": "list[tuple[float, float]]",
    "split_channels": "list[Buffer]",
    "write_file": "None",
}
DEFAULT_RETURN = "Buffer"

# Annotations for parameters the .pyx declares without a type, or types it
# declares too loosely (bare `list`) for a useful stub.
PARAM_OVERRIDES = {
    ("concat", "buffers"): "list[Buffer]",
    ("distort_mark", "markers"): "Sequence[float]",
    ("grain_position", "positions"): "list[float] | None",
    ("grain_reorder", "order"): "list[int] | None",
    ("grain_repitch", "pitch_curve"): "list[tuple[float, float]] | None",
    ("grain_rerhythm", "ratios"): "list[float] | None",
    ("grain_rerhythm", "times"): "list[float] | None",
    ("grain_timewarp", "stretch_curve"): "list[tuple[float, float]] | None",
    ("interleave", "buffers"): "list[Buffer]",
    ("mix", "buffers"): "list[Buffer]",
    ("mix", "gains"): "list[float] | None",
    ("pan_envelope", "points"): "list[tuple[float, float]]",
    ("phase_invert", "samples"): "Buffer | BufferLike",
    ("retime", "buf"): "Buffer",
    ("rotor", "buf"): "Buffer",
    ("scramble", "buf"): "Buffer",
    ("spin", "buf"): "Buffer",
    ("splinter", "buf"): "Buffer",
    ("synth_chord", "midi_notes"): "Sequence[int]",
    ("zigzag", "times"): "Sequence[float]",
}


def parse_pyx(path: Path) -> dict[str, list[tuple[str, str | None, str | None]]]:
    """Extract (name, cython_type, default) for every module-level `def`.

    Cross-validated against inspect.signature on the compiled module; see
    tests/test_signatures.py, which asserts the agreement continuously.
    """
    src = path.read_text()
    out: dict[str, list[tuple[str, str | None, str | None]]] = {}

    for m in re.finditer(r"^def (\w+)\(", src, re.M):
        name = m.group(1)
        # Walk to the matching close paren so multi-line signatures work.
        i = m.end() - 1
        depth = 0
        j = i
        while j < len(src):
            if src[j] == "(":
                depth += 1
            elif src[j] == ")":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        sig = src[i + 1 : j]

        # Split on top-level commas only (defaults may contain brackets).
        parts: list[str] = []
        depth = 0
        cur = ""
        for ch in sig:
            if ch in "([{":
                depth += 1
            elif ch in ")]}":
                depth -= 1
            if ch == "," and depth == 0:
                parts.append(cur)
                cur = ""
            else:
                cur += ch
        if cur.strip():
            parts.append(cur)

        args = []
        for p in parts:
            p = " ".join(p.split())
            if not p:
                continue
            if "=" in p:
                lhs, rhs = p.split("=", 1)
                default = rhs.strip()
            else:
                lhs, default = p, None
            lhs = lhs.replace("not None", "").strip()
            toks = lhs.split()
            pname = toks[-1]
            ctype = " ".join(toks[:-1]) if len(toks) > 1 else None
            args.append((pname, ctype, default))

        if name in out:
            raise SystemExit(
                f"error: {name} is defined more than once in {path.name}; "
                "the later definition silently shadows the earlier one"
            )
        out[name] = args
    return out


def first_doc_line(src: str, func: str) -> str | None:
    """Return the first line of a function's docstring, for the stub summary."""
    m = re.search(
        rf'^def {re.escape(func)}\((?:[^)]*\n?)*?\):\n\s+"""(.*?)$', src, re.M
    )
    if not m:
        return None
    line = m.group(1).strip()
    if not line:  # docstring opens on the following line
        m2 = re.search(
            rf'^def {re.escape(func)}\((?:[^)]*\n?)*?\):\n\s+"""\n\s+(.*?)$', src, re.M
        )
        line = m2.group(1).strip() if m2 else ""
    return line.rstrip('"').strip() or None


def annotate(func: str, pname: str, ctype: str | None) -> str:
    override = PARAM_OVERRIDES.get((func, pname))
    if override:
        return override
    if ctype is None:
        raise SystemExit(
            f"error: {func}({pname}) is untyped in _core.pyx and has no entry "
            f"in PARAM_OVERRIDES. Add one to scripts/gen_stubs.py."
        )
    if ctype == "list":
        raise SystemExit(
            f"error: {func}({pname}) is a bare `list`; add a precise annotation "
            f"to PARAM_OVERRIDES in scripts/gen_stubs.py."
        )
    if ctype not in TYPE_MAP:
        raise SystemExit(
            f"error: unmapped Cython type {ctype!r} on {func}({pname}). "
            f"Add it to TYPE_MAP in scripts/gen_stubs.py."
        )
    return TYPE_MAP[ctype]


def render(sigs, pyx_src: str) -> str:
    lines: list[str] = []
    for func in sorted(sigs):
        params = []
        for pname, ctype, default in sigs[func]:
            ann = annotate(func, pname, ctype)
            params.append(f"{pname}: {ann}" + (f" = {default}" if default else ""))

        ret = RETURNS.get(func, DEFAULT_RETURN)
        oneline = f"def {func}({', '.join(params)}) -> {ret}:"

        if len(oneline) <= 88:
            lines.append(oneline)
        else:
            lines.append(f"def {func}(")
            for p in params:
                lines.append(f"    {p},")
            lines.append(f") -> {ret}:")

        doc = first_doc_line(pyx_src, func)
        if doc:
            escaped = doc.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
            lines.append(f'    """{escaped}"""')
        lines.append("    ...")
        lines.append("")

    return "\n".join(lines)


def build() -> str:
    pyx_src = PYX.read_text()
    sigs = parse_pyx(PYX)

    existing = PYI.read_text()
    if SENTINEL in existing:
        header = existing.split(SENTINEL)[0].rstrip("\n")
    else:
        raise SystemExit(
            f"error: {PYI} has no sentinel line. Add this line where the "
            f"generated section should begin:\n\n{SENTINEL}"
        )

    body = render(sigs, pyx_src)
    return f"{header}\n\n{SENTINEL}\n# Regenerate with: make stubs\n\n{body}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed stub differs from the generated one",
    )
    args = ap.parse_args()

    generated = build()

    if args.check:
        if PYI.read_text() != generated:
            print(
                f"error: {PYI.relative_to(REPO)} is out of date with "
                f"{PYX.relative_to(REPO)}.\nRun: make stubs",
                file=sys.stderr,
            )
            return 1
        print(f"{PYI.relative_to(REPO)} is up to date")
        return 0

    PYI.write_text(generated)
    n = len(parse_pyx(PYX))
    print(f"wrote {PYI.relative_to(REPO)} ({n} functions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
